### PR TITLE
Update the title and permlink

### PR DESCRIPTION
**Pull request by DRsfish**
The permlink and title are misspelled, it should be "Staking" rather than "Stacking".

### CODE REVIEW

**Review by balajmarius — APPROVED** [review]

**Comment by balajmarius** [comment]
Looks good, let's merge!

**Review by yzhuang — APPROVED** [review]

**Comment by wangchun** [comment]
@DRsfish permalink, not permlink.

**Comment by DRsfish** [comment]
Got it. Thanks for clarifying.

**Review by AlphaMale1st — COMMENTED** [review]
@A1pha

**Pull request merged**
